# Site settings
title: voxbox.io
email: talk@voxbox.io
description: > # this means to ignore newlines until "baseurl:"
  telecom application development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.voxbox.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

